# Generated by Django 3.0 on 2020-11-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20201122_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecords',
            name='dateIssued',
            field=models.DateField(default='2020-11-23'),
        ),
    ]
