# Generated by Django 3.0 on 2020-11-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20201123_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecords',
            name='book1',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='studentrecords',
            name='book2',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='studentrecords',
            name='book3',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
