# Generated by Django 3.0 on 2020-12-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20201123_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecords',
            name='book1_date',
            field=models.DateField(default='2020-12-03'),
        ),
        migrations.AddField(
            model_name='studentrecords',
            name='book2_date',
            field=models.DateField(default='2020-12-03'),
        ),
        migrations.AddField(
            model_name='studentrecords',
            name='book3_date',
            field=models.DateField(default='2020-12-03'),
        ),
        migrations.AlterField(
            model_name='studentrecords',
            name='dateIssued',
            field=models.DateField(default='2020-12-03'),
        ),
    ]
